name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Tailwind CSS
        run: |
          npm install
          npm run build:css
          npm run copy:js

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Generate Go code from templ files
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Build Go Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o survivor-app ./cmd/server

      - name: Stop Systemd Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl stop survivor-app
        
      - name: Copy Files to Droplet via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "survivor-app,static/css,static/js"
          target: "/var/www/survivor-app/"
          overwrite: true

      - name: Restart Systemd Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl restart survivor-app
